branch-defaults:
  master:
    environment: find-my-tutor
    group_suffix: null
global:
  application_name: find-my-tutor
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
